### ISSUE TITLE
Element Actions bug

### ISSUE THREAD

**Issue by lboaretto** [webdna/boris#3]
Hello,

Thank you for this awesome plugin!

I tried deleting by selecting a few items, and received this error:

```
[error] [php] in_array() expects parameter 2 to be array, string given (/home/usr/craft/plugins/boris/services/BorisService.php:37)
Stack trace:
#0 /home/usr/craft/plugins/boris/BorisPlugin.php(83): Craft\BorisService->invincible()
#1 /home/usr/craft/app/framework/base/CComponent.php(567): Craft\BorisPlugin->Craft\{closure}()
#2 /home/usr/craft/app/services/ElementsService.php(2391): Craft\ElementsService->raiseEvent()
#3 /home/usr/craft/app/controllers/ElementIndexController.php(188): Craft\ElementsService->onBeforePerformAction()
#4 /home/usr/craft/app/framework/web/actions/CInlineAction.php(49): Craft\ElementIndexController->actionPerformAction()
#5 /home/usr/craft/app/framework/web/CController.php(308): CInlineAction->runWithParams()
#6 /home/usr/craft/app/framework/web/CController.php(286): Craft\ElementIndexController->runAction()
#7 /home/usr/craft/app/framework/web/CController.php(265): Craft\ElementIndexController->runActionWithFilters()
#8 /home/usr/craft/app/framework/web/CWebApplication.php(282): Craft\ElementIndexController->run()
#9 /home/usr/craft/app/etc/web/WebApp.php(823): Craft\WebApp->runController()
#10 /home/usr/craft/app/etc/web/WebApp.php(287): Craft\WebApp->_processActionRequest()
#11 /home/usr/craft/app/framework/base/CApplication.php(185): Craft\WebApp->processRequest()
#12 /home/usr/craft/app/index.php(62): Craft\WebApp->run()
#13 /home/usr/public/index.php(27): require_once()
REQUEST_URI=/index.php/admi9/actions/elementIndex/performAction
```

**Comment by nfourtythree** [comment]
Hey @lboaretto 

The only way I could replicate the error that you mentioned was if there were no invincible (protected) elements.

I have pushed an update in the latest release that should make this more robust.

You can either update through the admin panel as normal or get the latest version here: https://github.com/webdna/boris/releases/tag/1.1.2

Hope this helps!

**Comment by lboaretto** [comment]
Thank you so much @nfourtythree :smiley:
